# Generated by Django 4.0.2 on 2022-02-19 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thewall', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='day',
            old_name='feet_done',
            new_name='current_feet_done',
        ),
        migrations.RenameField(
            model_name='day',
            old_name='number',
            new_name='day_no',
        ),
        migrations.RemoveField(
            model_name='day',
            name='profile',
        ),
        migrations.AddField(
            model_name='day',
            name='profile_no',
            field=models.PositiveSmallIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='day',
            name='total_feet_done',
            field=models.PositiveSmallIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
